# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAvisoSalir(object):
    def setupUi(self, DialogAvisoSalir):
        DialogAvisoSalir.setObjectName("DialogAvisoSalir")
        DialogAvisoSalir.resize(367, 205)
        self.buttonBoxSalir = QtWidgets.QDialogButtonBox(DialogAvisoSalir)
        self.buttonBoxSalir.setGeometry(QtCore.QRect(20, 160, 341, 32))
        self.buttonBoxSalir.setStyleSheet("font: 8pt \"Impact\";")
        self.buttonBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBoxSalir.setCenterButtons(True)
        self.buttonBoxSalir.setObjectName("buttonBoxSalir")
        self.label = QtWidgets.QLabel(DialogAvisoSalir)
        self.label.setGeometry(QtCore.QRect(10, 20, 361, 41))
        self.label.setStyleSheet("font: 75 14pt \"Impact\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogAvisoSalir)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 111, 71))
        self.label_2.setStyleSheet("background-image: url(:/salir/salir.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(DialogAvisoSalir)
        self.buttonBoxSalir.accepted.connect(DialogAvisoSalir.accept)
        self.buttonBoxSalir.rejected.connect(DialogAvisoSalir.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAvisoSalir)

    def retranslateUi(self, DialogAvisoSalir):
        _translate = QtCore.QCoreApplication.translate
        DialogAvisoSalir.setWindowTitle(_translate("DialogAvisoSalir", "Dialog"))
        self.label.setText(_translate("DialogAvisoSalir", "¿ Está seguro de que desea salir ?"))
import salir_rc
